#!/usr/bin/env python3
"""Generate cover for '바이브 너머의 엔지니어' using PIL.

Concept: Typography-led, charcoal-navy gradient + faded code line + bronze
boundary line. No metallic/neon. Pragmatic-Programmer-adjacent restraint.
"""
from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageChops
import os
import random

W, H = 1600, 2560
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cover.png")

# Palette
BG_TOP = (14, 20, 32)         # #0E1420
BG_BOT = (26, 34, 56)         # #1A2238
WARM_WHITE = (242, 239, 233)  # #F2EFE9
COOL_GREY = (154, 163, 178)   # #9AA3B2
BRONZE = (201, 168, 106)      # #C9A86A
DIM_GREY = (122, 130, 144)    # #7A8290
CODE_GREY = (90, 100, 120)    # faded pseudo-code

# Fonts
FONT_MYUNGJO = "/System/Library/Fonts/Supplemental/AppleMyungjo.ttf"
FONT_GOTHIC_TTC = "/System/Library/Fonts/AppleSDGothicNeo.ttc"
FONT_NOTO_KR = os.path.expanduser("~/Library/Fonts/NotoSansKR-VariableFont_wght.ttf")
FONT_HELV = "/System/Library/Fonts/Helvetica.ttc"
FONT_MENLO = "/System/Library/Fonts/Menlo.ttc"


def load_font(path, size, index=0):
    try:
        if path.endswith(".ttc"):
            return ImageFont.truetype(path, size, index=index)
        return ImageFont.truetype(path, size)
    except Exception as err:
        print(f"font load failed {path}: {err}")
        return ImageFont.load_default()


# 1. Vertical gradient background
img = Image.new("RGB", (W, H), BG_TOP)
px = img.load()
for y in range(H):
    t = (y / (H - 1)) ** 1.15
    r = int(BG_TOP[0] + (BG_BOT[0] - BG_TOP[0]) * t)
    g = int(BG_TOP[1] + (BG_BOT[1] - BG_TOP[1]) * t)
    b = int(BG_TOP[2] + (BG_BOT[2] - BG_TOP[2]) * t)
    row = (r, g, b)
    for x in range(W):
        px[x, y] = row

# 2. Subtle paper grain (low-intensity noise blended additively)
random.seed(7)
noise = Image.new("L", (W, H), 0)
noise_px = noise.load()
for y in range(H):
    for x in range(W):
        noise_px[x, y] = random.randint(0, 18)
noise = noise.filter(ImageFilter.GaussianBlur(0.6))
noise_rgb = Image.merge("RGB", (noise, noise, noise))
img = ImageChops.add(img, noise_rgb)

draw = ImageDraw.Draw(img)


def text_size(text, font):
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[2] - bbox[0], bbox[3] - bbox[1]


# 3. Faded pseudo-code lines at top — "읽지 않은 코드" motif
code_font = load_font(FONT_MENLO, 30)
code_lines = [
    "// auto-generated by agent  ·  2026",
    "function shipIt(prompt) {",
    "  const code = ai.complete(prompt);",
    "  return merge(code);  // did you read it?",
    "}",
]
code_layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
code_draw = ImageDraw.Draw(code_layer)
y_code = 260
for line in code_lines:
    code_draw.text((220, y_code), line, font=code_font,
                   fill=(CODE_GREY[0], CODE_GREY[1], CODE_GREY[2], 120))
    y_code += 56

# Blur the code layer to simulate "not-quite-read"
code_layer = code_layer.filter(ImageFilter.GaussianBlur(1.4))
img.paste(code_layer, (0, 0), code_layer)

draw = ImageDraw.Draw(img)

# 4. Bronze horizontal boundary line — "너머"의 경계
line_y = 1080
draw.line([(220, line_y), (W - 220, line_y)], fill=BRONZE, width=2)

# Subtle doorway notch in the middle (suggesting passage)
notch_w = 14
notch_h = 26
cx = W // 2
draw.line([(cx - notch_w, line_y - notch_h), (cx - notch_w, line_y)],
          fill=BRONZE, width=2)
draw.line([(cx + notch_w, line_y - notch_h), (cx + notch_w, line_y)],
          fill=BRONZE, width=2)
draw.line([(cx - notch_w, line_y - notch_h), (cx + notch_w, line_y - notch_h)],
          fill=BRONZE, width=2)

# 5. Main title (명조, 두 줄, 선 아래)
title_font = load_font(FONT_MYUNGJO, 200)
title_line1 = "바이브 너머의"
title_line2 = "엔지니어"

tw1, th1 = text_size(title_line1, title_font)
tw2, th2 = text_size(title_line2, title_font)

title_y1 = line_y + 120
draw.text(((W - tw1) // 2, title_y1), title_line1, font=title_font, fill=WARM_WHITE)

title_y2 = title_y1 + th1 + 40
draw.text(((W - tw2) // 2, title_y2), title_line2, font=title_font, fill=WARM_WHITE)

# 6. Short bronze accent under title
accent_y = title_y2 + th2 + 80
draw.line([(cx - 70, accent_y), (cx + 70, accent_y)], fill=BRONZE, width=3)

# 7. Korean subtitle — two lines, cool grey, sans-serif
sub_font = load_font(FONT_NOTO_KR, 58)
sub_line1 = "Agentic Coding 시대,"
sub_line2 = "무엇을 위임하고 무엇을 끝까지 알아야 하는가"

sw1, sh1 = text_size(sub_line1, sub_font)
sw2, sh2 = text_size(sub_line2, sub_font)

sub_y1 = accent_y + 80
draw.text(((W - sw1) // 2, sub_y1), sub_line1, font=sub_font, fill=COOL_GREY)
sub_y2 = sub_y1 + sh1 + 24
draw.text(((W - sw2) // 2, sub_y2), sub_line2, font=sub_font, fill=COOL_GREY)

# 8. English tagline — small, bronze
eng_font = load_font(FONT_HELV, 38)
eng_line = "Beyond the Vibe  —  An Engineer's Stance"
ew, eh = text_size(eng_line, eng_font)
eng_y = sub_y2 + sh2 + 130
draw.text(((W - ew) // 2, eng_y), eng_line, font=eng_font, fill=BRONZE)

# 9. Author at bottom
author_font = load_font(FONT_GOTHIC_TTC, 52, index=2)
author_text = "Toby-AI"
aw, ah = text_size(author_text, author_font)
draw.text(((W - aw) // 2, H - 240), author_text, font=author_font, fill=DIM_GREY)

# 10. Footer tag
mark_font_kr = load_font(FONT_GOTHIC_TTC, 26, index=0)
mark = "· 에세이형 기술서 ·"
mw, mh = text_size(mark, mark_font_kr)
draw.text(((W - mw) // 2, H - 150), mark, font=mark_font_kr, fill=DIM_GREY)

# Save
img.save(OUT, "PNG", optimize=True)
print(f"saved: {OUT}")
print(f"size : {os.path.getsize(OUT) / 1024:.1f} KB")
print(f"dim  : {W}x{H}")
